### ISSUE TITLE
Massif is MS Windows only?

### ISSUE THREAD

**Issue by toeklk** [FTSRG/massif#36] opened 2015-10-29 14:22 UTC
Hi,

I didn't see any mentioning of the fact that massif is currently limited to MS Windows in the documentation, but when trying to run massif on OS X, I get an NoClassDefFoundError in 

```
br.com.embraer.massif.commandevaluation.client.util.MatlabRunningManager.getRunningMatlabs(MatlabRunningManager.java:97)
```

reading
```java
Kernel32 kernel32 = (Kernel32) Native.loadLibrary(Kernel32.class, W32APIOptions.UNICODE_OPTIONS);
```

From what I see in this file, it looks like massif currently only supports MS Windows?

**Comment by abelhegedus** [comment] 2015-10-29 14:26
The Command Evaluation based connector uses the Windows registry (see #4). Massif itself is not platform dependent as far as we know. Try the MatlabControl based connector, which should work (https://github.com/FTSRG/massif/wiki/UserGuide#accessing-simulink-models).

**Comment by abelhegedus** [comment] 2015-11-04 19:27
Duplicate of #4

**Closed by abelhegedus** 2015-11-04 19:27 UTC
Labels: duplicate
